[package]
name = "pillar"
version = "0.2.0"
entrypoint = "src/pillar.typ"
authors = ["Mc-Zen <https://github.com/Mc-Zen>"]
license = "MIT"
description = "Faster column specifications for tables."
compiler = "0.11.0"

homepage = "https://github.com/Mc-Zen/pillar"
repository = "https://github.com/Mc-Zen/pillar"
keywords = ["table", "columns", "latex", "S column"]
categories = ["visualization", "layout"]
exclude = ["/docs/*"]